apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubevision.fullname" . }}
  labels:
    {{- include "kubevision.labels" . | nindent 4 }}
data:
  config.yaml: |
    server:
      port: {{ .Values.config.server.port }}
    database:
      driver: {{ .Values.config.database.driver }}
      {{- if not .Values.existingSecret }}
      dsn: {{ .Values.config.database.dsn }}
      {{- end }}
      max_open_conns: {{ .Values.config.database.maxOpenConns }}
      max_idle_conns: {{ .Values.config.database.maxIdleConns }}
      conn_max_lifetime: {{ .Values.config.database.connMaxLifetime }}
      conn_max_idle_time: {{ .Values.config.database.connMaxIdleTime }}
      ping_timeout: {{ .Values.config.database.pingTimeout }}
    auth:
      access_token_ttl: {{ .Values.config.auth.accessTokenTTL }}
      refresh_token_ttl: {{ .Values.config.auth.refreshTokenTTL }}
      public_key:
        enabled: {{ .Values.config.auth.publicKey.enabled }}
        rp_id: {{ .Values.config.auth.publicKey.rpId | quote }}
        rp_display_name: {{ .Values.config.auth.publicKey.rpDisplayName | quote }}
        origins:
          {{- toYaml .Values.config.auth.publicKey.origins | nindent 10 }}
        user_verification: {{ .Values.config.auth.publicKey.userVerification | quote }}
        counter_policy: {{ .Values.config.auth.publicKey.counterPolicy | quote }}
        challenge_ttl: {{ .Values.config.auth.publicKey.challengeTTL }}
    kubernetes:
      informer_resync: {{ .Values.config.kubernetes.informerResync }}
      crd_discovery_interval: {{ .Values.config.kubernetes.crdDiscoveryInterval }}
    audit:
      enabled: {{ .Values.config.audit.enabled }}
      retention_days: {{ .Values.config.audit.retentionDays }}
    oauth:
      enabled: {{ .Values.config.oauth.enabled }}
    registry:
      allowed_registries:
        {{- toYaml .Values.config.registry.allowedRegistries | nindent 8 }}
      allowed_auth_hosts:
        {{- toYaml .Values.config.registry.allowedAuthHosts | nindent 8 }}
      allow_private: {{ .Values.config.registry.allowPrivate }}
      allow_http: {{ .Values.config.registry.allowHTTP }}
    {{- if .Values.config.plugins.prometheus.url }}
    plugins:
      prometheus:
        url: {{ .Values.config.plugins.prometheus.url }}
      {{- if .Values.config.plugins.grafana.url }}
      grafana:
        url: {{ .Values.config.plugins.grafana.url }}
      {{- end }}
      {{- if .Values.config.plugins.argocd.url }}
      argocd:
        url: {{ .Values.config.plugins.argocd.url }}
      {{- end }}
    {{- end }}
